server:
  port: 1010

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/bfansheng/spring-cloud-config.git
          search-paths: demo
      label: master

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1000/eureka/